import tkinter
master_window = tkinter.Tk()

#menu
menu1 = tkinter.Menu(master_window)
master_window.config(menu=menu1)
filemenu = tkinter.Menu(menu1, tearoff = 0)
menu1.add_cascade(label = "File", menu = filemenu)
filemenu.add_command(label = "New Text File")
filemenu.add_command(label = "New File")
filemenu.add_command(label = "New Window")
filemenu.add_command(label = "New Window with Profile")
filemenu.add_separator()
filemenu.add_command(label = "Open File")
filemenu.add_command(label = "Open Folder")
filemenu.add_command(label = "Open Workspace from File...")
filemenu.add_command(label = "Open Recent")
filemenu.add_separator()
filemenu.add_command(label = "Add Folder to Workspace")
filemenu.add_command(label = "Save Workspace As...")
filemenu.add_command(label = "Duplicate Workspace")
filemenu.add_separator()
filemenu.add_command(label = "Save")
filemenu.add_command(label = "Save As...")
filemenu.add_command(label = "Save All")
filemenu.add_separator()
filemenu.add_command(label = "Share")
filemenu.add_separator()
filemenu.add_command(label = "Auto Save")
filemenu.add_command(label = "Preferences")
filemenu.add_separator()
filemenu.add_command(label = "Revert File")
filemenu.add_command(label = "Close Editor")
filemenu.add_command(label = "Close Folder")
filemenu.add_command(label = "Close Window")
filemenu.add_separator()
filemenu.add_command(label = "Exit", command = master_window.destroy)

terminalmenu = tkinter.Menu(menu1, tearoff=0)
menu1.add_cascade(label="Terminal", menu=terminalmenu)
terminalmenu.add_command(label="New terminal")
terminalmenu.add_command(label="Split terminal")
terminalmenu.add_separator()
terminalmenu.add_command(label="Run Task...")
terminalmenu.add_command(label="Run Build Task...")
terminalmenu.add_command(label="Run Active File")
terminalmenu.add_command(label="Run Selected Task")
terminalmenu.add_separator()
terminalmenu.add_command(label="Show Running Task...")
terminalmenu.add_command(label="Restart Running Task...")
terminalmenu.add_command(label="Terminate Task...")
terminalmenu.add_separator()
terminalmenu.add_command(label="Configure Task")
terminalmenu.add_command(label="Configure Default Build Task")
terminalmenu.add_separator()
terminalmenu.add_command(label = "Exit", command = master_window.destroy)

master_window.mainloop()